
export const FETCH_LATEST_POSTS_REQUEST = 'FETCH_LATEST_POSTS_REQUEST';
export const FETCH_LATEST_POSTS_RESPONSE = 'FETCH_LATEST_POSTS_RESPONSE';
export const FETCH_LATEST_POSTS_ERROR = 'FETCH_LATEST_POSTS_ERROR';