
export const FETCH_LATEST_POSTS_REQUEST = 'FETCH_LATEST_POSTS_REQUEST';
export const FETCH_LATEST_POSTS_RESPONSE = 'FETCH_LATEST_POSTS_RESPONSE';
export const FETCH_LATEST_POSTS_ERROR = 'FETCH_LATEST_POSTS_ERROR';

export const FETCH_POST_DETAILS_REQUEST = 'FETCH_POST_DETAILS_REQUEST';
export const FETCH_POST_DETAILS_RESPONSE = 'FETCH_POST_DETAILS_RESPONSE';
export const FETCH_POST_DETAILS_ERROR = 'FETCH_POST_DETAILS_ERROR';